export const SET_CONTACT = "ADD_CONTACT"
export const SET_CREATE_CONTACT_ERROR = "SET_CREATE_CONTACT_ERROR"
export const SET_MANAGE_CONTACT_ERROR = "SET_MANAGE_CONTACT_ERROR"

export const CREATE_CONTACT_REQUEST = "CREATE_CONTACT_REQUEST"
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS"
export const CREATE_CONTACT_FAILURE = "CREATE_CONTACT_FAILURE"

export const GET_ALL_CONTACTS_REQUEST = "GET_ALL_CONTACTS_REQUEST"
export const GET_ALL_CONTACTS_SUCCESS = "GET_ALL_CONTACTS_SUCCESS"
export const GET_ALL_CONTACTS_FAILURE = "GET_ALL_CONTACTS_FAILURE"

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST"
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS"
export const DELETE_CONTACT_FAILURE = "DELETE_CONTACT_FAILURE"

